#! /bin/sh
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config initial_polarity 	second_child

bspc monitor -a 1 2 3 4 5 6 7 8 9 

bspc rule -a firefox floating=on

$HOME/src/dotfiles/feh/fehbg.sh $HOME/Dropbox/Wallpapers/wallhaven-73452.jpg
$HOME/src/toolbox/trayer.sh
