#! /bin/sh
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

if xrandr | grep -q "DP1 connected"
then
	bspc monitor DP1 -a 1 2 3 4 5 6 7 8 9 
	if xrandr | grep -q "VGA1 connected"
	then
		bspc monitor VGA1 -a 1
	fi
else 
	bspc monitor -d 1 2 3 4 5 6 7 8 9 
fi

bspc rule -a firefox floating=on

$HOME/src/dotfiles/feh/fehbg.sh $HOME/Dropbox/Wallpapers/wallhaven-73452.jpg
$HOME/src/toolbox/trayer.sh
