#! /bin/sh
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

if xrandr | grep -q "HDMI1 connected"
then
	bspc monitor HDMI1 -n 0 -d 1 2 3 4 5 6 7 8 9 
else 
	bspc monitor -d 1 2 3 4 5 6 7 8 9 
fi

bspc rule -a firefox floating=on

$HOME/.config/bspwm/panel/panel &
$HOME/src/toolbox/fehbg
$HOME/src/toolbox/trayer.sh
