xset +fp /usr/share/fonts/artwiz-fonts
xset fp rehash

setxkbmap -layout "us,se" -option "grp: caps_toggle"
setxkbmap -device 14 -layout "us,se" -option "grp: caps_toggle"

#exec herbstluftwm
if xrandr | grep -q "HDMI1 connected"
then
	xrandr --output LVDS1 --off
	xrandr --output HDMI1 --auto
fi
sxhkd &
exec bspwm
