xset +fp /usr/share/fonts/artwiz-fonts
xset fp rehash

setxkbmap -layout "us,se" -option "grp: caps_toggle"
setxkbmap -device 14 -layout "us,se" -option "grp: caps_toggle"

$HOME/.config/monitor_setup.sh

sxhkd &
exec bspwm
